// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthAccount = `-- name: CreateAuthAccount :exec
INSERT INTO auth_account (id, account_id, provider_id, user_id, password)
VALUES ($1, $2, 'credential', $3, $4)
`

type CreateAuthAccountParams struct {
	ID        string  `json:"id"`
	AccountID string  `json:"account_id"`
	UserID    string  `json:"user_id"`
	Password  *string `json:"password"`
}

func (q *Queries) CreateAuthAccount(ctx context.Context, arg CreateAuthAccountParams) error {
	_, err := q.db.Exec(ctx, createAuthAccount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Password,
	)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_session (id, token, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthSessionParams struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const createAuthUser = `-- name: CreateAuthUser :exec
INSERT INTO auth_user (id, name, email, email_verified, username, display_username, user_registered_id)
VALUES ($1, $2, $3, false, $4, $4, $5)
`

type CreateAuthUserParams struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Email            string  `json:"email"`
	Username         *string `json:"username"`
	UserRegisteredID string  `json:"user_registered_id"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) error {
	_, err := q.db.Exec(ctx, createAuthUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.UserRegisteredID,
	)
	return err
}

const createAuthVerification = `-- name: CreateAuthVerification :exec
INSERT INTO auth_verification (id, identifier, value, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthVerificationParams struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthVerification(ctx context.Context, arg CreateAuthVerificationParams) error {
	_, err := q.db.Exec(ctx, createAuthVerification,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthSessionByToken = `-- name: DeleteAuthSessionByToken :exec
DELETE FROM auth_session
WHERE token = $1
`

func (q *Queries) DeleteAuthSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteAuthSessionByToken, token)
	return err
}

const markAuthUserEmailVerified = `-- name: MarkAuthUserEmailVerified :exec
UPDATE auth_user
SET email_verified = true,
    updated_at = now()
WHERE user_registered_id = $1
`

func (q *Queries) MarkAuthUserEmailVerified(ctx context.Context, userRegisteredID string) error {
	_, err := q.db.Exec(ctx, markAuthUserEmailVerified, userRegisteredID)
	return err
}

const passwordResetVerificationByToken = `-- name: PasswordResetVerificationByToken :one
SELECT id, identifier
FROM auth_verification
WHERE identifier LIKE 'password-reset:%'
  AND value = $1
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type PasswordResetVerificationByTokenRow struct {
	ID         string `json:"id"`
	Identifier string `json:"identifier"`
}

func (q *Queries) PasswordResetVerificationByToken(ctx context.Context, value string) (PasswordResetVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, passwordResetVerificationByToken, value)
	var i PasswordResetVerificationByTokenRow
	err := row.Scan(&i.ID, &i.Identifier)
	return i, err
}

const updateAuthAccountPassword = `-- name: UpdateAuthAccountPassword :exec
UPDATE auth_account
SET password = $1,
    updated_at = now()
WHERE user_id = $2
  AND provider_id = 'credential'
`

type UpdateAuthAccountPasswordParams struct {
	Password *string `json:"password"`
	UserID   string  `json:"user_id"`
}

func (q *Queries) UpdateAuthAccountPassword(ctx context.Context, arg UpdateAuthAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthAccountPassword, arg.Password, arg.UserID)
	return err
}

const updateAuthAccountPasswordByRegisteredID = `-- name: UpdateAuthAccountPasswordByRegisteredID :exec
UPDATE auth_account
SET password = $1,
    updated_at = now()
WHERE user_id = (
    SELECT id
    FROM auth_user
    WHERE user_registered_id = $2
)
  AND provider_id = 'credential'
`

type UpdateAuthAccountPasswordByRegisteredIDParams struct {
	Password         *string `json:"password"`
	UserRegisteredID string  `json:"user_registered_id"`
}

func (q *Queries) UpdateAuthAccountPasswordByRegisteredID(ctx context.Context, arg UpdateAuthAccountPasswordByRegisteredIDParams) error {
	_, err := q.db.Exec(ctx, updateAuthAccountPasswordByRegisteredID, arg.Password, arg.UserRegisteredID)
	return err
}

const updateAuthUserImage = `-- name: UpdateAuthUserImage :exec
UPDATE auth_user
SET image = $1,
    updated_at = now()
WHERE user_registered_id = $2
`

type UpdateAuthUserImageParams struct {
	Image            *string `json:"image"`
	UserRegisteredID string  `json:"user_registered_id"`
}

func (q *Queries) UpdateAuthUserImage(ctx context.Context, arg UpdateAuthUserImageParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserImage, arg.Image, arg.UserRegisteredID)
	return err
}

const updateAuthUserName = `-- name: UpdateAuthUserName :exec
UPDATE auth_user
SET name = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAuthUserNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateAuthUserName(ctx context.Context, arg UpdateAuthUserNameParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserName, arg.Name, arg.ID)
	return err
}

const updateAuthUserNameByRegisteredID = `-- name: UpdateAuthUserNameByRegisteredID :exec
UPDATE auth_user
SET name = $1,
    updated_at = now()
WHERE user_registered_id = $2
`

type UpdateAuthUserNameByRegisteredIDParams struct {
	Name             string `json:"name"`
	UserRegisteredID string `json:"user_registered_id"`
}

func (q *Queries) UpdateAuthUserNameByRegisteredID(ctx context.Context, arg UpdateAuthUserNameByRegisteredIDParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserNameByRegisteredID, arg.Name, arg.UserRegisteredID)
	return err
}

const userByEmailWithPassword = `-- name: UserByEmailWithPassword :one
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url,
       a.password
FROM auth_user u
JOIN auth_account a ON a.user_id = u.id AND a.provider_id = 'credential'
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.email = $1
`

type UserByEmailWithPasswordRow struct {
	ID               string  `json:"id"`
	UserRegisteredID string  `json:"user_registered_id"`
	Name             string  `json:"name"`
	Username         string  `json:"username"`
	Email            string  `json:"email"`
	EmailVerified    bool    `json:"email_verified"`
	Image            string  `json:"image"`
	Bio              string  `json:"bio"`
	HeaderImageUrl   string  `json:"header_image_url"`
	Password         *string `json:"password"`
}

func (q *Queries) UserByEmailWithPassword(ctx context.Context, email string) (UserByEmailWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, userByEmailWithPassword, email)
	var i UserByEmailWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.UserRegisteredID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Bio,
		&i.HeaderImageUrl,
		&i.Password,
	)
	return i, err
}

const userByIDOrRegisteredID = `-- name: UserByIDOrRegisteredID :one
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url
FROM auth_user u
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.id = $1 OR u.user_registered_id = $1
`

type UserByIDOrRegisteredIDRow struct {
	ID               string `json:"id"`
	UserRegisteredID string `json:"user_registered_id"`
	Name             string `json:"name"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	EmailVerified    bool   `json:"email_verified"`
	Image            string `json:"image"`
	Bio              string `json:"bio"`
	HeaderImageUrl   string `json:"header_image_url"`
}

func (q *Queries) UserByIDOrRegisteredID(ctx context.Context, id string) (UserByIDOrRegisteredIDRow, error) {
	row := q.db.QueryRow(ctx, userByIDOrRegisteredID, id)
	var i UserByIDOrRegisteredIDRow
	err := row.Scan(
		&i.ID,
		&i.UserRegisteredID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Bio,
		&i.HeaderImageUrl,
	)
	return i, err
}

const userByRegisteredID = `-- name: UserByRegisteredID :one
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url
FROM auth_user u
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.user_registered_id = $1
`

type UserByRegisteredIDRow struct {
	ID               string `json:"id"`
	UserRegisteredID string `json:"user_registered_id"`
	Name             string `json:"name"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	EmailVerified    bool   `json:"email_verified"`
	Image            string `json:"image"`
	Bio              string `json:"bio"`
	HeaderImageUrl   string `json:"header_image_url"`
}

func (q *Queries) UserByRegisteredID(ctx context.Context, userRegisteredID string) (UserByRegisteredIDRow, error) {
	row := q.db.QueryRow(ctx, userByRegisteredID, userRegisteredID)
	var i UserByRegisteredIDRow
	err := row.Scan(
		&i.ID,
		&i.UserRegisteredID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Bio,
		&i.HeaderImageUrl,
	)
	return i, err
}

const userBySessionToken = `-- name: UserBySessionToken :one
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url
FROM auth_session s
JOIN auth_user u ON u.id = s.user_id
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE s.token = $1
  AND s.expires_at > now()
`

type UserBySessionTokenRow struct {
	ID               string `json:"id"`
	UserRegisteredID string `json:"user_registered_id"`
	Name             string `json:"name"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	EmailVerified    bool   `json:"email_verified"`
	Image            string `json:"image"`
	Bio              string `json:"bio"`
	HeaderImageUrl   string `json:"header_image_url"`
}

func (q *Queries) UserBySessionToken(ctx context.Context, token string) (UserBySessionTokenRow, error) {
	row := q.db.QueryRow(ctx, userBySessionToken, token)
	var i UserBySessionTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserRegisteredID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Bio,
		&i.HeaderImageUrl,
	)
	return i, err
}
