// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoint.sql

package dbsql

import (
	"context"
)

const getEventHandlerCheckpoint = `-- name: GetEventHandlerCheckpoint :one
SELECT commit_position::bigint, prepare_position::bigint
FROM projector_checkpoint
WHERE name = $1
`

type GetEventHandlerCheckpointRow struct {
	CommitPosition  int64 `json:"commit_position"`
	PreparePosition int64 `json:"prepare_position"`
}

func (q *Queries) GetEventHandlerCheckpoint(ctx context.Context, name string) (GetEventHandlerCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getEventHandlerCheckpoint, name)
	var i GetEventHandlerCheckpointRow
	err := row.Scan(&i.CommitPosition, &i.PreparePosition)
	return i, err
}

const upsertEventHandlerCheckpoint = `-- name: UpsertEventHandlerCheckpoint :exec
INSERT INTO projector_checkpoint (id, name, commit_position, prepare_position, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (name) DO UPDATE
SET commit_position = EXCLUDED.commit_position,
    prepare_position = EXCLUDED.prepare_position,
    updated_at = now()
`

type UpsertEventHandlerCheckpointParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	CommitPosition  int64  `json:"commit_position"`
	PreparePosition int64  `json:"prepare_position"`
}

func (q *Queries) UpsertEventHandlerCheckpoint(ctx context.Context, arg UpsertEventHandlerCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertEventHandlerCheckpoint,
		arg.ID,
		arg.Name,
		arg.CommitPosition,
		arg.PreparePosition,
	)
	return err
}
