// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CompleteTodoParams struct {
	CompletedAt              *string `json:"completed_at"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
	TodoId                   string  `json:"todo_id"`
}

type CompleteTodoStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CompleteTodo(tx *sqlite.Conn) *CompleteTodoStmt {
	const querySQL = `
UPDATE todo_items
SET completed = true,
    completed_at = ?1,
    last_event_commit_position = ?2,
    last_event_prepare_position = ?3,
    updated_at = ?1
WHERE todo_id = ?4
    `

	ps := &CompleteTodoStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CompleteTodoStmt) Run(
	params CompleteTodoParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if params.CompletedAt == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.CompletedAt)

	}
	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.TodoId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute completetodo SQL: %w", err)
	}

	return nil
}

func OnceCompleteTodo(
	tx *sqlite.Conn,
	params CompleteTodoParams,
) (
	err error,
) {
	ps := CompleteTodo(tx)

	return ps.Run(
		params,
	)
}
