// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateSubjectPiiKeyParams struct {
	SubjectId        string `json:"subject_id"`
	EncryptedDataKey string `json:"encrypted_data_key"`
	EncryptionNonce  string `json:"encryption_nonce"`
	KeyVersion       string `json:"key_version"`
}

type CreateSubjectPiiKeyStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateSubjectPiiKey(tx *sqlite.Conn) *CreateSubjectPiiKeyStmt {
	const querySQL = `
INSERT OR IGNORE INTO subject_pii_keys (subject_id, encrypted_data_key, encryption_nonce, key_version)
VALUES (?1, ?2, ?3, ?4)
    `

	ps := &CreateSubjectPiiKeyStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateSubjectPiiKeyStmt) Run(
	params CreateSubjectPiiKeyParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.SubjectId)

	bindIndex++
	stmt.BindText(bindIndex, params.EncryptedDataKey)

	bindIndex++
	stmt.BindText(bindIndex, params.EncryptionNonce)

	bindIndex++
	stmt.BindText(bindIndex, params.KeyVersion)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createsubjectpiikey SQL: %w", err)
	}

	return nil
}

func OnceCreateSubjectPiiKey(
	tx *sqlite.Conn,
	params CreateSubjectPiiKeyParams,
) (
	err error,
) {
	ps := CreateSubjectPiiKey(tx)

	return ps.Run(
		params,
	)
}
