// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateAuthVerificationParams struct {
	Id         string `json:"id"`
	Identifier string `json:"identifier"`
	Value      string `json:"value"`
	ExpiresAt  string `json:"expires_at"`
}

type CreateAuthVerificationStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateAuthVerification(tx *sqlite.Conn) *CreateAuthVerificationStmt {
	const querySQL = `
INSERT OR IGNORE INTO auth_verification (id, identifier, value, expires_at)
VALUES (?1, ?2, ?3, ?4)
    `

	ps := &CreateAuthVerificationStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateAuthVerificationStmt) Run(
	params CreateAuthVerificationParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.Identifier)

	bindIndex++
	stmt.BindText(bindIndex, params.Value)

	bindIndex++
	stmt.BindText(bindIndex, params.ExpiresAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createauthverification SQL: %w", err)
	}

	return nil
}

func OnceCreateAuthVerification(
	tx *sqlite.Conn,
	params CreateAuthVerificationParams,
) (
	err error,
) {
	ps := CreateAuthVerification(tx)

	return ps.Run(
		params,
	)
}
