// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateAuthSessionParams struct {
	Id        string `json:"id"`
	Token     string `json:"token"`
	UserId    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
}

type CreateAuthSessionStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateAuthSession(tx *sqlite.Conn) *CreateAuthSessionStmt {
	const querySQL = `
INSERT INTO auth_session (id, token, user_id, expires_at)
VALUES (?1, ?2, ?3, ?4)
    `

	ps := &CreateAuthSessionStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateAuthSessionStmt) Run(
	params CreateAuthSessionParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.Token)

	bindIndex++
	stmt.BindText(bindIndex, params.UserId)

	bindIndex++
	stmt.BindText(bindIndex, params.ExpiresAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createauthsession SQL: %w", err)
	}

	return nil
}

func OnceCreateAuthSession(
	tx *sqlite.Conn,
	params CreateAuthSessionParams,
) (
	err error,
) {
	ps := CreateAuthSession(tx)

	return ps.Run(
		params,
	)
}
