// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateAuthAccountParams struct {
	Id        string  `json:"id"`
	AccountId string  `json:"account_id"`
	UserId    string  `json:"user_id"`
	Password  *string `json:"password"`
}

type CreateAuthAccountStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateAuthAccount(tx *sqlite.Conn) *CreateAuthAccountStmt {
	const querySQL = `
INSERT OR IGNORE INTO auth_account (id, account_id, provider_id, user_id, password)
VALUES (?1, ?2, 'credential', ?3, ?4)
    `

	ps := &CreateAuthAccountStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateAuthAccountStmt) Run(
	params CreateAuthAccountParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.AccountId)

	bindIndex++
	stmt.BindText(bindIndex, params.UserId)

	bindIndex++
	if params.Password == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Password)

	}
	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createauthaccount SQL: %w", err)
	}

	return nil
}

func OnceCreateAuthAccount(
	tx *sqlite.Conn,
	params CreateAuthAccountParams,
) (
	err error,
) {
	ps := CreateAuthAccount(tx)

	return ps.Run(
		params,
	)
}
