// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type CreateAuthUserParams struct {
	Id               string  `json:"id"`
	Name             string  `json:"name"`
	Email            string  `json:"email"`
	Username         *string `json:"username"`
	UserRegisteredId string  `json:"user_registered_id"`
}

type CreateAuthUserStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func CreateAuthUser(tx *sqlite.Conn) *CreateAuthUserStmt {
	const querySQL = `
INSERT OR IGNORE INTO auth_user (id, name, email, email_verified, username, display_username, user_registered_id)
VALUES (?1, ?2, ?3, false, ?4, ?4, ?5)
    `

	ps := &CreateAuthUserStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *CreateAuthUserStmt) Run(
	params CreateAuthUserParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.Name)

	bindIndex++
	stmt.BindText(bindIndex, params.Email)

	bindIndex++
	if params.Username == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Username)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.UserRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute createauthuser SQL: %w", err)
	}

	return nil
}

func OnceCreateAuthUser(
	tx *sqlite.Conn,
	params CreateAuthUserParams,
) (
	err error,
) {
	ps := CreateAuthUser(tx)

	return ps.Run(
		params,
	)
}
