// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteTodoParams struct {
	DeletedAt                *string `json:"deleted_at"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
	TodoId                   string  `json:"todo_id"`
}

type DeleteTodoStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteTodo(tx *sqlite.Conn) *DeleteTodoStmt {
	const querySQL = `
UPDATE todo_items
SET deleted_at = ?1,
    last_event_commit_position = ?2,
    last_event_prepare_position = ?3,
    updated_at = ?1
WHERE todo_id = ?4
    `

	ps := &DeleteTodoStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteTodoStmt) Run(
	params DeleteTodoParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if params.DeletedAt == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.DeletedAt)

	}
	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.TodoId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deletetodo SQL: %w", err)
	}

	return nil
}

func OnceDeleteTodo(
	tx *sqlite.Conn,
	params DeleteTodoParams,
) (
	err error,
) {
	ps := DeleteTodo(tx)

	return ps.Run(
		params,
	)
}
