// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteAuthSessionByTokenStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteAuthSessionByToken(tx *sqlite.Conn) *DeleteAuthSessionByTokenStmt {
	const querySQL = `
DELETE FROM auth_session
WHERE token = ?1
    `

	ps := &DeleteAuthSessionByTokenStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteAuthSessionByTokenStmt) Run(
	token string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, token)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deleteauthsessionbytoken SQL: %w", err)
	}

	return nil
}

func OnceDeleteAuthSessionByToken(
	tx *sqlite.Conn,
	token string,
) (
	err error,
) {
	ps := DeleteAuthSessionByToken(tx)

	return ps.Run(
		token,
	)
}
