// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteAuthVerificationsByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteAuthVerificationsByRegisteredId(tx *sqlite.Conn) *DeleteAuthVerificationsByRegisteredIdStmt {
	const querySQL = `
DELETE FROM auth_verification
WHERE identifier IN ('email:' || ?1, 'password-reset:' || ?1)
    `

	ps := &DeleteAuthVerificationsByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteAuthVerificationsByRegisteredIdStmt) Run(
	userRegisteredId *string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if userRegisteredId == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *userRegisteredId)

	}
	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deleteauthverificationsbyregisteredid SQL: %w", err)
	}

	return nil
}

func OnceDeleteAuthVerificationsByRegisteredId(
	tx *sqlite.Conn,
	userRegisteredId *string,
) (
	err error,
) {
	ps := DeleteAuthVerificationsByRegisteredId(tx)

	return ps.Run(
		userRegisteredId,
	)
}
