// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteAuthAccountsByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteAuthAccountsByRegisteredId(tx *sqlite.Conn) *DeleteAuthAccountsByRegisteredIdStmt {
	const querySQL = `
DELETE FROM auth_account
WHERE user_id IN (
    SELECT id
    FROM auth_user
    WHERE user_registered_id = ?1
)
    `

	ps := &DeleteAuthAccountsByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteAuthAccountsByRegisteredIdStmt) Run(
	userRegisteredId string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deleteauthaccountsbyregisteredid SQL: %w", err)
	}

	return nil
}

func OnceDeleteAuthAccountsByRegisteredId(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	err error,
) {
	ps := DeleteAuthAccountsByRegisteredId(tx)

	return ps.Run(
		userRegisteredId,
	)
}
