// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteSubjectPiiKeyStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteSubjectPiiKey(tx *sqlite.Conn) *DeleteSubjectPiiKeyStmt {
	const querySQL = `
DELETE FROM subject_pii_keys
WHERE subject_id = ?1
    `

	ps := &DeleteSubjectPiiKeyStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteSubjectPiiKeyStmt) Run(
	subjectId string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, subjectId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deletesubjectpiikey SQL: %w", err)
	}

	return nil
}

func OnceDeleteSubjectPiiKey(
	tx *sqlite.Conn,
	subjectId string,
) (
	err error,
) {
	ps := DeleteSubjectPiiKey(tx)

	return ps.Run(
		subjectId,
	)
}
