// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type DeleteAuthUserByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func DeleteAuthUserByRegisteredId(tx *sqlite.Conn) *DeleteAuthUserByRegisteredIdStmt {
	const querySQL = `
DELETE FROM auth_user
WHERE user_registered_id = ?1
    `

	ps := &DeleteAuthUserByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *DeleteAuthUserByRegisteredIdStmt) Run(
	userRegisteredId string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute deleteauthuserbyregisteredid SQL: %w", err)
	}

	return nil
}

func OnceDeleteAuthUserByRegisteredId(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	err error,
) {
	ps := DeleteAuthUserByRegisteredId(tx)

	return ps.Run(
		userRegisteredId,
	)
}
