// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type GetEventHandlerCheckpointRes struct {
	CommitPosition  int64 `json:"commit_position"`
	PreparePosition int64 `json:"prepare_position"`
}

type GetEventHandlerCheckpointStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func GetEventHandlerCheckpoint(tx *sqlite.Conn) *GetEventHandlerCheckpointStmt {
	const querySQL = `
SELECT commit_position, prepare_position
FROM projector_checkpoint
WHERE name = ?1
    `

	ps := &GetEventHandlerCheckpointStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *GetEventHandlerCheckpointStmt) Run(
	name string,
) (
	res *GetEventHandlerCheckpointRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, name)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := GetEventHandlerCheckpointRes{}
		row.CommitPosition = stmt.ColumnInt64(0)
		row.PreparePosition = stmt.ColumnInt64(1)
		res = &row
	}

	return res, nil
}

func OnceGetEventHandlerCheckpoint(
	tx *sqlite.Conn,
	name string,
) (
	res *GetEventHandlerCheckpointRes,
	err error,
) {
	ps := GetEventHandlerCheckpoint(tx)

	return ps.Run(
		name,
	)
}
