// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type InsertCreatedTodoParams struct {
	TodoId                   string `json:"todo_id"`
	UserRegisteredId         string `json:"user_registered_id"`
	Title                    string `json:"title"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	CreatedAt                string `json:"created_at"`
}

type InsertCreatedTodoStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func InsertCreatedTodo(tx *sqlite.Conn) *InsertCreatedTodoStmt {
	const querySQL = `
INSERT INTO todo_items (todo_id, user_registered_id, title, completed, completed_at, deleted_at, last_event_commit_position, last_event_prepare_position, created_at, updated_at)
VALUES (?1, ?2, ?3, false, null, null, ?4, ?5, ?6, ?6)
ON CONFLICT (todo_id) DO NOTHING
    `

	ps := &InsertCreatedTodoStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *InsertCreatedTodoStmt) Run(
	params InsertCreatedTodoParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.TodoId)

	bindIndex++
	stmt.BindText(bindIndex, params.UserRegisteredId)

	bindIndex++
	stmt.BindText(bindIndex, params.Title)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.CreatedAt)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute insertcreatedtodo SQL: %w", err)
	}

	return nil
}

func OnceInsertCreatedTodo(
	tx *sqlite.Conn,
	params InsertCreatedTodoParams,
) (
	err error,
) {
	ps := InsertCreatedTodo(tx)

	return ps.Run(
		params,
	)
}
