// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ListTodosRes struct {
	TodoId    string `json:"todo_id"`
	Title     string `json:"title"`
	Completed int64  `json:"completed"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ListTodosStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ListTodos(tx *sqlite.Conn) *ListTodosStmt {
	const querySQL = `
SELECT todo_id, title, completed, created_at, updated_at
FROM todo_items
WHERE user_registered_id = ?1
  AND deleted_at IS NULL
ORDER BY created_at DESC, todo_id DESC
    `

	ps := &ListTodosStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ListTodosStmt) Run(
	userRegisteredId string,
) (
	res []ListTodosRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := ListTodosRes{}
		row.TodoId = stmt.ColumnText(0)
		row.Title = stmt.ColumnText(1)
		row.Completed = stmt.ColumnInt64(2)
		row.CreatedAt = stmt.ColumnText(3)
		row.UpdatedAt = stmt.ColumnText(4)
		res = append(res, row)
	}

	return res, nil
}

func OnceListTodos(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	res []ListTodosRes,
	err error,
) {
	ps := ListTodos(tx)

	return ps.Run(
		userRegisteredId,
	)
}
