// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type MarkAuthUserEmailVerifiedStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func MarkAuthUserEmailVerified(tx *sqlite.Conn) *MarkAuthUserEmailVerifiedStmt {
	const querySQL = `
UPDATE auth_user
SET email_verified = true,
    updated_at = CURRENT_TIMESTAMP
WHERE user_registered_id = ?1
    `

	ps := &MarkAuthUserEmailVerifiedStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *MarkAuthUserEmailVerifiedStmt) Run(
	userRegisteredId string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute markauthuseremailverified SQL: %w", err)
	}

	return nil
}

func OnceMarkAuthUserEmailVerified(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	err error,
) {
	ps := MarkAuthUserEmailVerified(tx)

	return ps.Run(
		userRegisteredId,
	)
}
