// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAccount struct {
	ID                    string             `json:"id"`
	AccountID             string             `json:"account_id"`
	ProviderID            string             `json:"provider_id"`
	UserID                string             `json:"user_id"`
	AccessToken           *string            `json:"access_token"`
	RefreshToken          *string            `json:"refresh_token"`
	IDToken               *string            `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 *string            `json:"scope"`
	Password              *string            `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID             string             `json:"id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Token          string             `json:"token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IpAddress      *string            `json:"ip_address"`
	UserAgent      *string            `json:"user_agent"`
	UserID         string             `json:"user_id"`
	ImpersonatedBy *string            `json:"impersonated_by"`
}

type AuthUser struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	EmailVerified    bool               `json:"email_verified"`
	Image            *string            `json:"image"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Username         *string            `json:"username"`
	DisplayUsername  *string            `json:"display_username"`
	Role             *string            `json:"role"`
	Banned           *bool              `json:"banned"`
	BanReason        *string            `json:"ban_reason"`
	BanExpires       pgtype.Timestamptz `json:"ban_expires"`
	UserRegisteredID string             `json:"user_registered_id"`
}

type AuthVerification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProfileStat struct {
	UserID                   string             `json:"user_id"`
	Name                     *string            `json:"name"`
	Username                 *string            `json:"username"`
	Email                    *string            `json:"email"`
	Image                    *string            `json:"image"`
	Bio                      *string            `json:"bio"`
	HeaderImageUrl           *string            `json:"header_image_url"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type ProjectorCheckpoint struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	CommitPosition  int64              `json:"commit_position"`
	PreparePosition int64              `json:"prepare_position"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TodoItem struct {
	TodoID                   string             `json:"todo_id"`
	UserRegisteredID         string             `json:"user_registered_id"`
	Title                    string             `json:"title"`
	Completed                bool               `json:"completed"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}
