// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type PasswordResetVerificationByTokenRes struct {
	Id         string `json:"id"`
	Identifier string `json:"identifier"`
}

type PasswordResetVerificationByTokenStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func PasswordResetVerificationByToken(tx *sqlite.Conn) *PasswordResetVerificationByTokenStmt {
	const querySQL = `
SELECT id, identifier
FROM auth_verification
WHERE identifier LIKE 'password-reset:%'
  AND value = ?1
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
    `

	ps := &PasswordResetVerificationByTokenStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *PasswordResetVerificationByTokenStmt) Run(
	value string,
) (
	res *PasswordResetVerificationByTokenRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, value)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := PasswordResetVerificationByTokenRes{}
		row.Id = stmt.ColumnText(0)
		row.Identifier = stmt.ColumnText(1)
		res = &row
	}

	return res, nil
}

func OncePasswordResetVerificationByToken(
	tx *sqlite.Conn,
	value string,
) (
	res *PasswordResetVerificationByTokenRes,
	err error,
) {
	ps := PasswordResetVerificationByToken(tx)

	return ps.Run(
		value,
	)
}
