// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package dbsql

import (
	"context"
)

const upsertProfileBio = `-- name: UpsertProfileBio :exec
INSERT INTO profile_stats (user_id, bio, last_event_commit_position, last_event_prepare_position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = now()
`

type UpsertProfileBioParams struct {
	UserID                   string  `json:"user_id"`
	Bio                      *string `json:"bio"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

func (q *Queries) UpsertProfileBio(ctx context.Context, arg UpsertProfileBioParams) error {
	_, err := q.db.Exec(ctx, upsertProfileBio,
		arg.UserID,
		arg.Bio,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
	)
	return err
}

const upsertProfileHeaderImage = `-- name: UpsertProfileHeaderImage :exec
INSERT INTO profile_stats (user_id, header_image_url, last_event_commit_position, last_event_prepare_position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    header_image_url = EXCLUDED.header_image_url,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = now()
`

type UpsertProfileHeaderImageParams struct {
	UserID                   string  `json:"user_id"`
	HeaderImageUrl           *string `json:"header_image_url"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

func (q *Queries) UpsertProfileHeaderImage(ctx context.Context, arg UpsertProfileHeaderImageParams) error {
	_, err := q.db.Exec(ctx, upsertProfileHeaderImage,
		arg.UserID,
		arg.HeaderImageUrl,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
	)
	return err
}

const upsertProfileImage = `-- name: UpsertProfileImage :exec
INSERT INTO profile_stats (user_id, image, last_event_commit_position, last_event_prepare_position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    image = EXCLUDED.image,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = now()
`

type UpsertProfileImageParams struct {
	UserID                   string  `json:"user_id"`
	Image                    *string `json:"image"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

func (q *Queries) UpsertProfileImage(ctx context.Context, arg UpsertProfileImageParams) error {
	_, err := q.db.Exec(ctx, upsertProfileImage,
		arg.UserID,
		arg.Image,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
	)
	return err
}

const upsertProfileName = `-- name: UpsertProfileName :exec
INSERT INTO profile_stats (user_id, name, last_event_commit_position, last_event_prepare_position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    name = EXCLUDED.name,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = now()
`

type UpsertProfileNameParams struct {
	UserID                   string  `json:"user_id"`
	Name                     *string `json:"name"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

func (q *Queries) UpsertProfileName(ctx context.Context, arg UpsertProfileNameParams) error {
	_, err := q.db.Exec(ctx, upsertProfileName,
		arg.UserID,
		arg.Name,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
	)
	return err
}

const upsertRegisteredProfileUser = `-- name: UpsertRegisteredProfileUser :exec
INSERT INTO profile_stats (user_id, name, username, email, last_event_commit_position, last_event_prepare_position)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    name = EXCLUDED.name,
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = now()
`

type UpsertRegisteredProfileUserParams struct {
	UserID                   string  `json:"user_id"`
	Name                     *string `json:"name"`
	Username                 *string `json:"username"`
	Email                    *string `json:"email"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

func (q *Queries) UpsertRegisteredProfileUser(ctx context.Context, arg UpsertRegisteredProfileUserParams) error {
	_, err := q.db.Exec(ctx, upsertRegisteredProfileUser,
		arg.UserID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
	)
	return err
}
