// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ProfileUserRes struct {
	UserId         string `json:"user_id"`
	Name           string `json:"name"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	Image          string `json:"image"`
	Bio            string `json:"bio"`
	HeaderImageUrl string `json:"header_image_url"`
}

type ProfileUserStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ProfileUser(tx *sqlite.Conn) *ProfileUserStmt {
	const querySQL = `
SELECT user_id,
       coalesce(name, '') AS name,
       coalesce(username, '') AS username,
       coalesce(email, '') AS email,
       coalesce(image, '') AS image,
       coalesce(bio, '') AS bio,
       coalesce(header_image_url, '') AS header_image_url
FROM profile_stats
WHERE user_id = ?1
    `

	ps := &ProfileUserStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ProfileUserStmt) Run(
	userId string,
) (
	res *ProfileUserRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userId)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := ProfileUserRes{}
		row.UserId = stmt.ColumnText(0)
		row.Name = stmt.ColumnText(1)
		row.Username = stmt.ColumnText(2)
		row.Email = stmt.ColumnText(3)
		row.Image = stmt.ColumnText(4)
		row.Bio = stmt.ColumnText(5)
		row.HeaderImageUrl = stmt.ColumnText(6)
		res = &row
	}

	return res, nil
}

func OnceProfileUser(
	tx *sqlite.Conn,
	userId string,
) (
	res *ProfileUserRes,
	err error,
) {
	ps := ProfileUser(tx)

	return ps.Run(
		userId,
	)
}
