// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type RenameTodoParams struct {
	Title                    string `json:"title"`
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	UpdatedAt                string `json:"updated_at"`
	TodoId                   string `json:"todo_id"`
}

type RenameTodoStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func RenameTodo(tx *sqlite.Conn) *RenameTodoStmt {
	const querySQL = `
UPDATE todo_items
SET title = ?1,
    last_event_commit_position = ?2,
    last_event_prepare_position = ?3,
    updated_at = ?4
WHERE todo_id = ?5
    `

	ps := &RenameTodoStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *RenameTodoStmt) Run(
	params RenameTodoParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Title)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.UpdatedAt)

	bindIndex++
	stmt.BindText(bindIndex, params.TodoId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute renametodo SQL: %w", err)
	}

	return nil
}

func OnceRenameTodo(
	tx *sqlite.Conn,
	params RenameTodoParams,
) (
	err error,
) {
	ps := RenameTodo(tx)

	return ps.Run(
		params,
	)
}
