// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ReopenTodoParams struct {
	LastEventCommitPosition  int64  `json:"last_event_commit_position"`
	LastEventPreparePosition int64  `json:"last_event_prepare_position"`
	UpdatedAt                string `json:"updated_at"`
	TodoId                   string `json:"todo_id"`
}

type ReopenTodoStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ReopenTodo(tx *sqlite.Conn) *ReopenTodoStmt {
	const querySQL = `
UPDATE todo_items
SET completed = false,
    completed_at = null,
    last_event_commit_position = ?1,
    last_event_prepare_position = ?2,
    updated_at = ?3
WHERE todo_id = ?4
    `

	ps := &ReopenTodoStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ReopenTodoStmt) Run(
	params ReopenTodoParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++
	stmt.BindText(bindIndex, params.UpdatedAt)

	bindIndex++
	stmt.BindText(bindIndex, params.TodoId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute reopentodo SQL: %w", err)
	}

	return nil
}

func OnceReopenTodo(
	tx *sqlite.Conn,
	params ReopenTodoParams,
) (
	err error,
) {
	ps := ReopenTodo(tx)

	return ps.Run(
		params,
	)
}
