// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package dbsql

import (
	"context"
)

const resetEventHandlerCheckpoints = `-- name: ResetEventHandlerCheckpoints :exec
DELETE FROM projector_checkpoint
`

func (q *Queries) ResetEventHandlerCheckpoints(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetEventHandlerCheckpoints)
	return err
}

const resetReadModelAuthAccounts = `-- name: ResetReadModelAuthAccounts :exec
DELETE FROM auth_account
`

func (q *Queries) ResetReadModelAuthAccounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelAuthAccounts)
	return err
}

const resetReadModelAuthSessions = `-- name: ResetReadModelAuthSessions :exec
DELETE FROM auth_session
`

func (q *Queries) ResetReadModelAuthSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelAuthSessions)
	return err
}

const resetReadModelAuthUsers = `-- name: ResetReadModelAuthUsers :exec
DELETE FROM auth_user
`

func (q *Queries) ResetReadModelAuthUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelAuthUsers)
	return err
}

const resetReadModelAuthVerifications = `-- name: ResetReadModelAuthVerifications :exec
DELETE FROM auth_verification
`

func (q *Queries) ResetReadModelAuthVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelAuthVerifications)
	return err
}

const resetReadModelProfiles = `-- name: ResetReadModelProfiles :exec
DELETE FROM profile_stats
`

func (q *Queries) ResetReadModelProfiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelProfiles)
	return err
}

const resetReadModelTodos = `-- name: ResetReadModelTodos :exec
DELETE FROM todo_items
`

func (q *Queries) ResetReadModelTodos(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetReadModelTodos)
	return err
}
