// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type ResetReadModelProfilesStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func ResetReadModelProfiles(tx *sqlite.Conn) *ResetReadModelProfilesStmt {
	const querySQL = `
DELETE FROM profile_stats
    `

	ps := &ResetReadModelProfilesStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *ResetReadModelProfilesStmt) Run() (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute resetreadmodelprofiles SQL: %w", err)
	}

	return nil
}

func OnceResetReadModelProfiles(
	tx *sqlite.Conn,
) (
	err error,
) {
	ps := ResetReadModelProfiles(tx)

	return ps.Run()
}
