// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subject_pii_keys.sql

package dbsql

import (
	"context"
)

const createSubjectPiiKey = `-- name: CreateSubjectPiiKey :exec
INSERT INTO subject_pii_keys (subject_id, encrypted_data_key, encryption_nonce, key_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (subject_id) DO NOTHING
`

type CreateSubjectPiiKeyParams struct {
	SubjectID        string `json:"subject_id"`
	EncryptedDataKey string `json:"encrypted_data_key"`
	EncryptionNonce  string `json:"encryption_nonce"`
	KeyVersion       string `json:"key_version"`
}

func (q *Queries) CreateSubjectPiiKey(ctx context.Context, arg CreateSubjectPiiKeyParams) error {
	_, err := q.db.Exec(ctx, createSubjectPiiKey,
		arg.SubjectID,
		arg.EncryptedDataKey,
		arg.EncryptionNonce,
		arg.KeyVersion,
	)
	return err
}

const deleteSubjectPiiKey = `-- name: DeleteSubjectPiiKey :exec
DELETE FROM subject_pii_keys
WHERE subject_id = $1
`

func (q *Queries) DeleteSubjectPiiKey(ctx context.Context, subjectID string) error {
	_, err := q.db.Exec(ctx, deleteSubjectPiiKey, subjectID)
	return err
}

const subjectPiiKey = `-- name: SubjectPiiKey :one
SELECT subject_id, encrypted_data_key, encryption_nonce, key_version
FROM subject_pii_keys
WHERE subject_id = $1
`

type SubjectPiiKeyRow struct {
	SubjectID        string `json:"subject_id"`
	EncryptedDataKey string `json:"encrypted_data_key"`
	EncryptionNonce  string `json:"encryption_nonce"`
	KeyVersion       string `json:"key_version"`
}

func (q *Queries) SubjectPiiKey(ctx context.Context, subjectID string) (SubjectPiiKeyRow, error) {
	row := q.db.QueryRow(ctx, subjectPiiKey, subjectID)
	var i SubjectPiiKeyRow
	err := row.Scan(
		&i.SubjectID,
		&i.EncryptedDataKey,
		&i.EncryptionNonce,
		&i.KeyVersion,
	)
	return i, err
}
