// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type SubjectPiiKeyRes struct {
	SubjectId        string `json:"subject_id"`
	EncryptedDataKey string `json:"encrypted_data_key"`
	EncryptionNonce  string `json:"encryption_nonce"`
	KeyVersion       string `json:"key_version"`
}

type SubjectPiiKeyStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func SubjectPiiKey(tx *sqlite.Conn) *SubjectPiiKeyStmt {
	const querySQL = `
SELECT subject_id, encrypted_data_key, encryption_nonce, key_version
FROM subject_pii_keys
WHERE subject_id = ?1
    `

	ps := &SubjectPiiKeyStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *SubjectPiiKeyStmt) Run(
	subjectId string,
) (
	res *SubjectPiiKeyRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, subjectId)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := SubjectPiiKeyRes{}
		row.SubjectId = stmt.ColumnText(0)
		row.EncryptedDataKey = stmt.ColumnText(1)
		row.EncryptionNonce = stmt.ColumnText(2)
		row.KeyVersion = stmt.ColumnText(3)
		res = &row
	}

	return res, nil
}

func OnceSubjectPiiKey(
	tx *sqlite.Conn,
	subjectId string,
) (
	res *SubjectPiiKeyRes,
	err error,
) {
	ps := SubjectPiiKey(tx)

	return ps.Run(
		subjectId,
	)
}
