// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTodo = `-- name: CompleteTodo :exec
UPDATE todo_items
SET completed = true,
    completed_at = $1,
    last_event_commit_position = $2,
    last_event_prepare_position = $3,
    updated_at = $1
WHERE todo_id = $4
`

type CompleteTodoParams struct {
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	TodoID                   string             `json:"todo_id"`
}

func (q *Queries) CompleteTodo(ctx context.Context, arg CompleteTodoParams) error {
	_, err := q.db.Exec(ctx, completeTodo,
		arg.CompletedAt,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
		arg.TodoID,
	)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
UPDATE todo_items
SET deleted_at = $1,
    last_event_commit_position = $2,
    last_event_prepare_position = $3,
    updated_at = $1
WHERE todo_id = $4
`

type DeleteTodoParams struct {
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	TodoID                   string             `json:"todo_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo,
		arg.DeletedAt,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
		arg.TodoID,
	)
	return err
}

const insertCreatedTodo = `-- name: InsertCreatedTodo :exec
INSERT INTO todo_items (todo_id, user_registered_id, title, completed, completed_at, deleted_at, last_event_commit_position, last_event_prepare_position, created_at, updated_at)
VALUES ($1, $2, $3, false, null, null, $4, $5, $6, $6)
ON CONFLICT (todo_id) DO NOTHING
`

type InsertCreatedTodoParams struct {
	TodoID                   string             `json:"todo_id"`
	UserRegisteredID         string             `json:"user_registered_id"`
	Title                    string             `json:"title"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertCreatedTodo(ctx context.Context, arg InsertCreatedTodoParams) error {
	_, err := q.db.Exec(ctx, insertCreatedTodo,
		arg.TodoID,
		arg.UserRegisteredID,
		arg.Title,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
		arg.CreatedAt,
	)
	return err
}

const listTodos = `-- name: ListTodos :many
SELECT todo_id, title, completed, created_at, updated_at
FROM todo_items
WHERE user_registered_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, todo_id DESC
`

type ListTodosRow struct {
	TodoID    string             `json:"todo_id"`
	Title     string             `json:"title"`
	Completed bool               `json:"completed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTodos(ctx context.Context, userRegisteredID string) ([]ListTodosRow, error) {
	rows, err := q.db.Query(ctx, listTodos, userRegisteredID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodosRow
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.TodoID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTodo = `-- name: RenameTodo :exec
UPDATE todo_items
SET title = $1,
    last_event_commit_position = $2,
    last_event_prepare_position = $3,
    updated_at = $4
WHERE todo_id = $5
`

type RenameTodoParams struct {
	Title                    string             `json:"title"`
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	TodoID                   string             `json:"todo_id"`
}

func (q *Queries) RenameTodo(ctx context.Context, arg RenameTodoParams) error {
	_, err := q.db.Exec(ctx, renameTodo,
		arg.Title,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
		arg.UpdatedAt,
		arg.TodoID,
	)
	return err
}

const reopenTodo = `-- name: ReopenTodo :exec
UPDATE todo_items
SET completed = false,
    completed_at = null,
    last_event_commit_position = $1,
    last_event_prepare_position = $2,
    updated_at = $3
WHERE todo_id = $4
`

type ReopenTodoParams struct {
	LastEventCommitPosition  int64              `json:"last_event_commit_position"`
	LastEventPreparePosition int64              `json:"last_event_prepare_position"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	TodoID                   string             `json:"todo_id"`
}

func (q *Queries) ReopenTodo(ctx context.Context, arg ReopenTodoParams) error {
	_, err := q.db.Exec(ctx, reopenTodo,
		arg.LastEventCommitPosition,
		arg.LastEventPreparePosition,
		arg.UpdatedAt,
		arg.TodoID,
	)
	return err
}
