// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateAuthAccountPasswordParams struct {
	Password *string `json:"password"`
	UserId   string  `json:"user_id"`
}

type UpdateAuthAccountPasswordStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateAuthAccountPassword(tx *sqlite.Conn) *UpdateAuthAccountPasswordStmt {
	const querySQL = `
UPDATE auth_account
SET password = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?2
  AND provider_id = 'credential'
    `

	ps := &UpdateAuthAccountPasswordStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateAuthAccountPasswordStmt) Run(
	params UpdateAuthAccountPasswordParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if params.Password == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Password)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.UserId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updateauthaccountpassword SQL: %w", err)
	}

	return nil
}

func OnceUpdateAuthAccountPassword(
	tx *sqlite.Conn,
	params UpdateAuthAccountPasswordParams,
) (
	err error,
) {
	ps := UpdateAuthAccountPassword(tx)

	return ps.Run(
		params,
	)
}
