// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateAuthAccountPasswordByRegisteredIdParams struct {
	Password         *string `json:"password"`
	UserRegisteredId string  `json:"user_registered_id"`
}

type UpdateAuthAccountPasswordByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateAuthAccountPasswordByRegisteredId(tx *sqlite.Conn) *UpdateAuthAccountPasswordByRegisteredIdStmt {
	const querySQL = `
UPDATE auth_account
SET password = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = (
    SELECT id
    FROM auth_user
    WHERE user_registered_id = ?2
)
  AND provider_id = 'credential'
    `

	ps := &UpdateAuthAccountPasswordByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateAuthAccountPasswordByRegisteredIdStmt) Run(
	params UpdateAuthAccountPasswordByRegisteredIdParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if params.Password == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Password)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.UserRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updateauthaccountpasswordbyregisteredid SQL: %w", err)
	}

	return nil
}

func OnceUpdateAuthAccountPasswordByRegisteredId(
	tx *sqlite.Conn,
	params UpdateAuthAccountPasswordByRegisteredIdParams,
) (
	err error,
) {
	ps := UpdateAuthAccountPasswordByRegisteredId(tx)

	return ps.Run(
		params,
	)
}
