// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateAuthUserNameParams struct {
	Name string `json:"name"`
	Id   string `json:"id"`
}

type UpdateAuthUserNameStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateAuthUserName(tx *sqlite.Conn) *UpdateAuthUserNameStmt {
	const querySQL = `
UPDATE auth_user
SET name = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
    `

	ps := &UpdateAuthUserNameStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateAuthUserNameStmt) Run(
	params UpdateAuthUserNameParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Name)

	bindIndex++
	stmt.BindText(bindIndex, params.Id)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updateauthusername SQL: %w", err)
	}

	return nil
}

func OnceUpdateAuthUserName(
	tx *sqlite.Conn,
	params UpdateAuthUserNameParams,
) (
	err error,
) {
	ps := UpdateAuthUserName(tx)

	return ps.Run(
		params,
	)
}
