// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateAuthUserImageParams struct {
	Image            *string `json:"image"`
	UserRegisteredId string  `json:"user_registered_id"`
}

type UpdateAuthUserImageStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateAuthUserImage(tx *sqlite.Conn) *UpdateAuthUserImageStmt {
	const querySQL = `
UPDATE auth_user
SET image = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_registered_id = ?2
    `

	ps := &UpdateAuthUserImageStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateAuthUserImageStmt) Run(
	params UpdateAuthUserImageParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	if params.Image == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Image)

	}
	bindIndex++
	stmt.BindText(bindIndex, params.UserRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updateauthuserimage SQL: %w", err)
	}

	return nil
}

func OnceUpdateAuthUserImage(
	tx *sqlite.Conn,
	params UpdateAuthUserImageParams,
) (
	err error,
) {
	ps := UpdateAuthUserImage(tx)

	return ps.Run(
		params,
	)
}
