// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpdateAuthUserNameByRegisteredIdParams struct {
	Name             string `json:"name"`
	UserRegisteredId string `json:"user_registered_id"`
}

type UpdateAuthUserNameByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpdateAuthUserNameByRegisteredId(tx *sqlite.Conn) *UpdateAuthUserNameByRegisteredIdStmt {
	const querySQL = `
UPDATE auth_user
SET name = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_registered_id = ?2
    `

	ps := &UpdateAuthUserNameByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpdateAuthUserNameByRegisteredIdStmt) Run(
	params UpdateAuthUserNameByRegisteredIdParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Name)

	bindIndex++
	stmt.BindText(bindIndex, params.UserRegisteredId)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute updateauthusernamebyregisteredid SQL: %w", err)
	}

	return nil
}

func OnceUpdateAuthUserNameByRegisteredId(
	tx *sqlite.Conn,
	params UpdateAuthUserNameByRegisteredIdParams,
) (
	err error,
) {
	ps := UpdateAuthUserNameByRegisteredId(tx)

	return ps.Run(
		params,
	)
}
