// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpsertEventHandlerCheckpointParams struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	CommitPosition  int64  `json:"commit_position"`
	PreparePosition int64  `json:"prepare_position"`
}

type UpsertEventHandlerCheckpointStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpsertEventHandlerCheckpoint(tx *sqlite.Conn) *UpsertEventHandlerCheckpointStmt {
	const querySQL = `
INSERT INTO projector_checkpoint (id, name, commit_position, prepare_position, updated_at)
VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO UPDATE
SET commit_position = EXCLUDED.commit_position,
    prepare_position = EXCLUDED.prepare_position,
    updated_at = CURRENT_TIMESTAMP
    `

	ps := &UpsertEventHandlerCheckpointStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpsertEventHandlerCheckpointStmt) Run(
	params UpsertEventHandlerCheckpointParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.Id)

	bindIndex++
	stmt.BindText(bindIndex, params.Name)

	bindIndex++
	stmt.BindInt64(bindIndex, params.CommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.PreparePosition)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute upserteventhandlercheckpoint SQL: %w", err)
	}

	return nil
}

func OnceUpsertEventHandlerCheckpoint(
	tx *sqlite.Conn,
	params UpsertEventHandlerCheckpointParams,
) (
	err error,
) {
	ps := UpsertEventHandlerCheckpoint(tx)

	return ps.Run(
		params,
	)
}
