// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UpsertProfileImageParams struct {
	UserId                   string  `json:"user_id"`
	Image                    *string `json:"image"`
	LastEventCommitPosition  int64   `json:"last_event_commit_position"`
	LastEventPreparePosition int64   `json:"last_event_prepare_position"`
}

type UpsertProfileImageStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UpsertProfileImage(tx *sqlite.Conn) *UpsertProfileImageStmt {
	const querySQL = `
INSERT INTO profile_stats (user_id, image, last_event_commit_position, last_event_prepare_position)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (user_id) DO UPDATE SET
    image = EXCLUDED.image,
    last_event_commit_position = EXCLUDED.last_event_commit_position,
    last_event_prepare_position = EXCLUDED.last_event_prepare_position,
    updated_at = CURRENT_TIMESTAMP
    `

	ps := &UpsertProfileImageStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UpsertProfileImageStmt) Run(
	params UpsertProfileImageParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.UserId)

	bindIndex++
	if params.Image == nil {
		stmt.BindNull(bindIndex)
	} else {
		stmt.BindText(bindIndex, *params.Image)

	}
	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventCommitPosition)

	bindIndex++
	stmt.BindInt64(bindIndex, params.LastEventPreparePosition)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute upsertprofileimage SQL: %w", err)
	}

	return nil
}

func OnceUpsertProfileImage(
	tx *sqlite.Conn,
	params UpsertProfileImageParams,
) (
	err error,
) {
	ps := UpsertProfileImage(tx)

	return ps.Run(
		params,
	)
}
