// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UserByRegisteredIdRes struct {
	Id               string `json:"id"`
	UserRegisteredId string `json:"user_registered_id"`
	Name             string `json:"name"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	EmailVerified    int64  `json:"email_verified"`
	Image            string `json:"image"`
	Bio              string `json:"bio"`
	HeaderImageUrl   string `json:"header_image_url"`
}

type UserByRegisteredIdStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UserByRegisteredId(tx *sqlite.Conn) *UserByRegisteredIdStmt {
	const querySQL = `
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url
FROM auth_user u
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.user_registered_id = ?1
    `

	ps := &UserByRegisteredIdStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UserByRegisteredIdStmt) Run(
	userRegisteredId string,
) (
	res *UserByRegisteredIdRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, userRegisteredId)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := UserByRegisteredIdRes{}
		row.Id = stmt.ColumnText(0)
		row.UserRegisteredId = stmt.ColumnText(1)
		row.Name = stmt.ColumnText(2)
		row.Username = stmt.ColumnText(3)
		row.Email = stmt.ColumnText(4)
		row.EmailVerified = stmt.ColumnInt64(5)
		row.Image = stmt.ColumnText(6)
		row.Bio = stmt.ColumnText(7)
		row.HeaderImageUrl = stmt.ColumnText(8)
		res = &row
	}

	return res, nil
}

func OnceUserByRegisteredId(
	tx *sqlite.Conn,
	userRegisteredId string,
) (
	res *UserByRegisteredIdRes,
	err error,
) {
	ps := UserByRegisteredId(tx)

	return ps.Run(
		userRegisteredId,
	)
}
