// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package dbsql

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UserByEmailWithPasswordRes struct {
	Id               string  `json:"id"`
	UserRegisteredId string  `json:"user_registered_id"`
	Name             string  `json:"name"`
	Username         string  `json:"username"`
	Email            string  `json:"email"`
	EmailVerified    int64   `json:"email_verified"`
	Image            string  `json:"image"`
	Bio              string  `json:"bio"`
	HeaderImageUrl   string  `json:"header_image_url"`
	Password         *string `json:"password"`
}

type UserByEmailWithPasswordStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func UserByEmailWithPassword(tx *sqlite.Conn) *UserByEmailWithPasswordStmt {
	const querySQL = `
SELECT u.id,
       u.user_registered_id,
       u.name,
       coalesce(u.username, '') AS username,
       u.email,
       u.email_verified,
       coalesce(u.image, '') AS image,
       coalesce(p.bio, '') AS bio,
       coalesce(p.header_image_url, '') AS header_image_url,
       a.password
FROM auth_user u
JOIN auth_account a ON a.user_id = u.id AND a.provider_id = 'credential'
LEFT JOIN profile_stats p ON p.user_id = u.user_registered_id
WHERE u.email = ?1
    `

	ps := &UserByEmailWithPasswordStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *UserByEmailWithPasswordStmt) Run(
	email string,
) (
	res *UserByEmailWithPasswordRes,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, email)

	bindIndex++

	// Execute the query
	if hasRow, err := stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := UserByEmailWithPasswordRes{}
		row.Id = stmt.ColumnText(0)
		row.UserRegisteredId = stmt.ColumnText(1)
		row.Name = stmt.ColumnText(2)
		row.Username = stmt.ColumnText(3)
		row.Email = stmt.ColumnText(4)
		row.EmailVerified = stmt.ColumnInt64(5)
		row.Image = stmt.ColumnText(6)
		row.Bio = stmt.ColumnText(7)
		row.HeaderImageUrl = stmt.ColumnText(8)
		isNullPassword := stmt.ColumnIsNull(9)
		if !isNullPassword {
			tmp := stmt.ColumnText(9)
			row.Password = &tmp
		}
		res = &row
	}

	return res, nil
}

func OnceUserByEmailWithPassword(
	tx *sqlite.Conn,
	email string,
) (
	res *UserByEmailWithPasswordRes,
	err error,
) {
	ps := UserByEmailWithPassword(tx)

	return ps.Run(
		email,
	)
}
